[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/studio"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200
